export { default as Route } from './components/Route.svelte'
export { default as Link } from './components/Link.svelte'
export { type Router, router } from './router'
export { type OptionsList, type Options, options } from './options'
export { type Path, type Query, type Hash, path, query, hash } from './location'
export { type LinkHandle, linkHandle } from '$lib/linkHandle'
export { type GetPathSegments, getPathSegments } from '$lib/getPathSegments'
